- name: Remove a file in the home directory only if it exists
  hosts: ubuntuazuser
  tasks:
  	- name: Remove a file in the home directory
      shell: rm $HOME/testfile.txt
      args:
      	removes: "$HOME/testfile.txt"
        warn: false
