-
  hosts: sap
  gather_facts: true
  become: true
  tasks:
    -
      name: delete checkmk-agent
      file:
          path: /home/adminazure/check-mk-agent-2.1.0p25-1.noarch.rpm
          state: absent
