-
  hosts: azsjlprod
  gather_facts: true
  become: true
  tasks:
    -
      name: delete cortex-agent
      file:
          path: /home/azsejalanprod/cortex-8.0.0.94458.rpm
          state: absent
      
